"""
Human-readable document titles.

Source documents in the corpus have opaque numeric filenames (22260.md,
22291.md, ...). This service turns each into a short human-readable title
via one lightweight LLM call, permanently cached on disk so no title is
ever generated twice. Falls back to the filename if the LLM fails.
"""

from __future__ import annotations

import json
import logging
import re
import threading
from pathlib import Path
from typing import Dict, List

from app.adapters.llm_client import LLMClient

logger = logging.getLogger(__name__)

DOCUMENTS_DIR = Path(__file__).resolve().parents[2] / "documents"
CACHE_PATH = Path("storage") / "doc_titles.json"
CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)

_llm = LLMClient()
_lock = threading.Lock()
_cache: Dict[str, str] = {}
_loaded = False


def _load_cache() -> None:
    global _loaded
    if _loaded:
        return
    if CACHE_PATH.exists():
        try:
            _cache.update(json.loads(CACHE_PATH.read_text(encoding="utf-8")))
        except Exception:
            logger.exception("Failed to load doc title cache")
    _loaded = True


def _save_cache() -> None:
    try:
        CACHE_PATH.write_text(
            json.dumps(_cache, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
    except Exception:
        logger.exception("Failed to persist doc title cache")


def _fallback_title(document_id: str) -> str:
    return document_id.replace("_", " ").replace(".md", "")


def _read_document_head(document_id: str, max_chars: int = 1200) -> str | None:
    """Read the first part of a corpus document; also handles ids stored
    with or without the .md extension."""
    candidates = [
        DOCUMENTS_DIR / document_id,
        DOCUMENTS_DIR / f"{document_id}.md",
    ]
    for path in candidates:
        if path.exists() and path.is_file():
            try:
                return path.read_text(encoding="utf-8", errors="ignore")[:max_chars]
            except Exception:
                return None
    return None


def _generate_title(document_id: str) -> str:
    # Uploaded documents already carry their original filename as a title.
    if document_id.startswith("upload-"):
        from app.services import session_documents

        name = session_documents.get_document_name(document_id)
        if name:
            return re.sub(r"\.(pdf|md|txt)$", "", name, flags=re.I)
        return _fallback_title(document_id)

    head = _read_document_head(document_id)
    if not head:
        return _fallback_title(document_id)

    prompt = f"""
Generate a short human-readable title for this policy document.

Rules:
- 3 to 8 words
- Title case
- No quotes, no punctuation at the end
- Name the program/policy if one is mentioned
- Return ONLY the title

Document excerpt:
{head}

Title:
""".strip()

    try:
        title = _llm.generate(prompt, temperature=0.1, max_tokens=30).strip()
        # Strip stray quotes/markdown the model may add.
        title = title.strip('"\u201c\u201d\'` ').splitlines()[0].strip()
        if 2 < len(title) <= 90:
            return title
    except Exception as e:
        logger.warning("Title generation failed for %s: %s", document_id, e)

    return _fallback_title(document_id)


def get_titles(document_ids: List[str]) -> Dict[str, str]:
    """Resolve titles for the given ids, generating (and caching) any that
    have never been seen before. Never generates a title twice."""
    _load_cache()

    result: Dict[str, str] = {}
    missing: List[str] = []

    for doc_id in dict.fromkeys(document_ids):  # dedupe, keep order
        if doc_id in _cache:
            result[doc_id] = _cache[doc_id]
        else:
            missing.append(doc_id)

    if missing:
        with _lock:
            for doc_id in missing:
                if doc_id in _cache:  # generated by a concurrent request
                    result[doc_id] = _cache[doc_id]
                    continue
                title = _generate_title(doc_id)
                _cache[doc_id] = title
                result[doc_id] = title
            _save_cache()

    return result
